Repository openthread/ot-ns, pull requests merged in 2020-08, with the labels that each got.

#69 [stress-tests] add commissioning stress test
  .github/workflows/stress.yml
  pylibs/otns/cli/OTNS.py
  pylibs/stress_tests/commissioning.py
  pylibs/unittests/OTNSTestCase.py
  pylibs/unittests/test_basic.py
Labels: continuous-integration

#72 [pixi.js] fix PIXI.js unable to fallback to Canvas
  script/pack-web
  web/site/bindata.go
  web/site/js/vis/ActionBar.js
  web/site/js/vis/Button.js
  web/site/js/vis/Node.js
  web/site/js/vis/PixiVisualizer.js
  web/site/js/vis/VObject.js
  web/site/js/vis/message.js
  web/site/js/vis/wrapper.js
  web/site/package.json
Labels: bug

#73 [grpcwebproxy] kills existing process
  web/web.go
Labels: enhancement

#81 [tests] Add test add node with ID
  pylibs/unittests/test_basic.py
Labels: continuous-integration

#79 [flags] use env OTNS_OT_CLI as OT executable if specified
  otns_main/otns_main.go
Labels: enhancement

#76 [replay] generate network visualization replay
  otns_main/otns_main.go
  visualize/grpc/grpcVisualizer.go
  visualize/grpc/pb/visualize_grpc.pb.go
  visualize/grpc/pb/visualize_grpc.proto
  visualize/grpc/replay/replay.go
  web/site/bindata.go
Labels: enhancement

#82 [visualization] add visualization log window
  web/site/bindata.go
  web/site/js/vis/ActionBar.js
  web/site/js/vis/LogWindow.js
  web/site/js/vis/PixiVisualizer.js
  web/site/package.json
Labels: enhancement

#85 [grpc] remove useless `grpcSimCtrl`
  visualize/grpc/grpcSimCtrl.go
Labels: P4, refactoring

#86 [grpc] fix command failure with node context
  .codecov.yml
  cli/CmdRunner.go
  web/site/bindata.go
  web/site/js/vis/PixiVisualizer.js
Labels: bug

#89 [web-visualization] fix visualization issue after refresh
  web/site/bindata.go
  web/site/js/vis/PixiVisualizer.js
Labels: P2, bug

#91 [unittests] Real mode tests wait for gRPC server to start
  pylibs/unittests/test_real.py
Labels: continuous-integration

#58 [cli] add `restore` flag for add command
  cli/CmdRunner.go
  cli/README.md
  cli/ast.go
  pylibs/otns/cli/OTNS.py
  pylibs/unittests/test_basic.py
  simulation/node.go
  simulation/node_config.go
Labels: enhancement

#93 [visualization] fix Log Window performance issue
  web/site/bindata.go
  web/site/js/vis/ActionBar.js
  web/site/js/vis/LogWindow.js
  web/site/js/vis/PixiVisualizer.js
Labels: enhancement
