Repository openthread/ot-ns, pull requests merged in 2020-07, with the labels that each got.

#37 [dispatcher] add real mode for real devices
  cmd/real/otns-silk-proxy/otns-silk-proxy.go
  dispatcher/dispatcher.go
  otns_main/otns_main.go
  script/install
  simulation/node.go
  simulation/simulation.go
  simulation/simulation_config.go
Labels: P2, enhancement

#39 [dispatcher] allow receive UDP events from remote nodes
  dispatcher/Node.go
  dispatcher/dispatcher.go
  dispatcher/event.go
Labels: enhancement

#42 [visualization] visualize transmit status emitting
  dispatcher/dispatcher.go
Labels: enhancement

#5 [simulation] support virtual time UART
  .github/workflows/test.yml
  dispatcher/dispatcher.go
  dispatcher/event.go
  otns_main/otns_main.go
  pylibs/examples/form_partition.py
  pylibs/unittests/OTNSTestCase.py
  pylibs/unittests/test_basic.py
  pylibs/unittests/test_commissioning.py
  pylibs/unittests/test_signals.py
  simulation/node.go
  simulation/simulation.go
  simulation/simulation_config.go
Labels: enhancement

#44 [grpc] add node_id argument to CtrlAddNode
  simulation/simulation.go
  simulation/simulationController.go
  visualize/SimulationController.go
  visualize/grpc/grpcServer.go
  visualize/grpc/grpcSimCtrl.go
  visualize/grpc/pb/visualize_grpc.pb.go
  visualize/grpc/pb/visualize_grpc.proto
  web/site/bindata.go
Labels: P2, enhancement

#45 [visualization] fix transmit event visualization
  dispatcher/dispatcher.go
Labels: bug

#46 [real] fix delete node error
  dispatcher/dispatcher.go
Labels: P2, bug

#41 [cli] add runcli package for common CLI logic
  cli/CmdRunner.go
  cli/runcli/runcli.go
  cli/runner.go
  cmd/real/otns-silk-proxy/otns-silk-proxy.go
Labels: refactoring

#47 [ot-cli] search for ot-cli executable in $PATH
  otns_main/otns_main.go
  simulation/node.go
  simulation/node_config.go
  simulation/simulation_config.go
Labels: enhancement

#43 [simulation] auto detects whether a node uses virtual time UART
  dispatcher/dispatcher.go
  otns_main/otns_main.go
  simulation/node.go
  simulation/simulation.go
  simulation/simulation_config.go
Labels: enhancement

#48 [cli] allow specify OT executable when adding nodes
  cli/CmdRunner.go
  cli/ast.go
  pylibs/otns/cli/OTNS.py
  simulation/node.go
  simulation/node_config.go
Labels: enhancement

#51 [real] do not wait for extaddr change from real devices
  dispatcher/dispatcher.go
Labels: enhancement

#52 [visualization] set simulation title
  cli/CmdRunner.go
  cli/README.md
  cli/ast.go
  pylibs/examples/farm.py
  pylibs/examples/form_partition.py
  pylibs/examples/ping.py
  pylibs/examples/simple.py
  pylibs/otns/cli/OTNS.py
  simulation/simulation.go
  simulation/simulationController.go
  visualize/SimulationController.go
  visualize/grpc/grpcField.go
  visualize/grpc/grpcServer.go
  visualize/grpc/grpcSimCtrl.go
  visualize/grpc/grpcVisualizer.go
  visualize/grpc/pb/visualize_grpc.pb.go
  visualize/grpc/pb/visualize_grpc.proto
  visualize/multi/multiVisualizer.go
  visualize/nopVisualizer.go
  visualize/types.go
  web/site/bindata.go
  web/site/js/vis/PixiVisualizer.js
  web/site/js/visualize.js
Labels: P2, enhancement

#53 [visualization] Improve HiDPI support
  web/site/bindata.go
  web/site/js/vis/Node.js
  web/site/js/vis/message.js
  web/site/js/visualize.js
Labels: P4, enhancement

#57 [scripts] Update dev tools
  go.mod
  script/setup-dev
  visualize/grpc/pb/visualize_grpc.pb.go
  web/site/bindata.go
Labels: P3

#55 [dispatcher] allow specify listen address
  cli/CmdRunner.go
  dispatcher/dispatcher.go
  otns_main/otns_main.go
  simulation/simulation.go
  simulation/simulation_config.go
  web/site/site.go
  web/site/site_test.go
  web/web.go
Labels: enhancement

#56 [visualization] Updates node texture when mode/role changes
  dispatcher/dispatcher.go
  go.mod
  types/types.go
  visualize/grpc/grpcField.go
  visualize/grpc/grpcVisualizer.go
  visualize/grpc/pb/visualize_grpc.pb.go
  visualize/grpc/pb/visualize_grpc.proto
  visualize/multi/multiVisualizer.go
  visualize/nopVisualizer.go
  visualize/types.go
  web/site/bindata.go
  web/site/js/vis/Node.js
  web/site/js/vis/PixiVisualizer.js
  web/site/js/visualize.js
Labels: enhancement

#50 [stress-tests] add the large_network_forming stress test
  .github/workflows/stress.yml
  pylibs/stress_tests/BaseStressTest.py
  pylibs/stress_tests/StressTestResult.py
  pylibs/stress_tests/large_network_forming.py
  pylibs/stress_tests/run_stress_suite.py
  script/test
Labels: continuous-integration, enhancement

#62 [scripts] skip running example form_partition.py
  script/test
Labels: P2, continuous-integration

#63 [doc] add id arg to add CLI command README
  cli/README.md
Labels: documentation

#66 [scripts] dev tools use fixed version
  go.mod
  script/setup-dev
  visualize/grpc/pb/visualize_grpc.pb.go
  visualize/grpc/pb/visualize_grpc.proto
  web/site/bindata.go
Labels: enhancement

#65 [real] allow set speed in real mode
  dispatcher/dispatcher.go
Labels: enhancement

#64 [grpc-service] remove control rpcs
  go.mod
  simulation/simulationController.go
  visualize/SimulationController.go
  visualize/grpc/grpcServer.go
  visualize/grpc/grpcSimCtrl.go
  visualize/grpc/pb/visualize_grpc.pb.go
  visualize/grpc/pb/visualize_grpc.proto
  web/site/bindata.go
  web/site/js/vis/ActionBar.js
  web/site/js/vis/PixiVisualizer.js
Labels: refactoring

#68 [ot-cli] kill ot-cli process with SIGTERM
  simulation/node.go
Labels: P2, bug

#71 [simulation] remove NodeMode for adding nodes
  dispatcher/dispatcher.go
  simulation/simulation.go
  visualize/grpc/grpcField.go
  visualize/grpc/grpcNode.go
  visualize/grpc/grpcVisualizer.go
  visualize/grpc/pb/visualize_grpc.pb.go
  visualize/grpc/pb/visualize_grpc.proto
  visualize/multi/multiVisualizer.go
  visualize/nopVisualizer.go
  visualize/types.go
  web/site/bindata.go
  web/site/js/vis/Node.js
  web/site/js/vis/PixiVisualizer.js
  web/site/js/visualize.js
Labels: refactoring

#70 [visualization] adjust with network info
  cli/CmdRunner.go
  cli/README.md
  cli/ast.go
  pylibs/examples/farm.py
  pylibs/examples/form_partition.py
  pylibs/examples/ping.py
  pylibs/examples/simple.py
  pylibs/otns/cli/OTNS.py
  simulation/simulation.go
  visualize/grpc/grpcField.go
  visualize/grpc/grpcVisualizer.go
  visualize/grpc/pb/visualize_grpc.pb.go
  visualize/grpc/pb/visualize_grpc.proto
  visualize/multi/multiVisualizer.go
  visualize/nopVisualizer.go
  visualize/types.go
  web/site/bindata.go
  web/site/js/vis/ActionBar.js
  web/site/js/vis/Node.js
  web/site/js/vis/PixiVisualizer.js
  web/site/js/vis/VObject.js
  web/site/js/vis/message.js
  web/site/js/visualize.js
Labels: enhancement
