Repository openthread/ot-ns, pull requests merged in 2020-09, with the labels that each got.

#97 [visualization] highlight selected links
  web/site/bindata.go
  web/site/js/vis/PixiVisualizer.js
Labels: enhancement

#96 [dispatcher] dump radio packets to STDOUT
  dispatcher/dispatcher.go
  otns_main/otns_main.go
  simulation/simulation.go
  simulation/simulation_config.go
Labels: P3, enhancement

#94 [stress-tests] add ping latency stress test
  .github/workflows/stress.yml
  cli/CmdRunner.go
  dispatcher/Node.go
  dispatcher/dispatcher.go
  pylibs/stress_tests/BaseStressTest.py
  pylibs/stress_tests/ping_latency.py
  types/types.go
  visualize/grpc/grpcField.go
  visualize/grpc/grpcNode.go
  visualize/grpc/grpcVisualizer.go
  visualize/multi/multiVisualizer.go
  visualize/types.go
Labels: continuous-integration

#101 [mle] remove secure data request mode bit
  .github/workflows/stress.yml
  .github/workflows/test.yml
  pylibs/unittests/test_real.py
  simulation/node.go
  types/types.go
  visualize/grpc/grpcVisualizer.go
  web/site/bindata.go
  web/site/js/vis/ActionBar.js
  web/site/js/vis/PixiVisualizer.js
Labels: enhancement
