Repository openthread/ot-ns, pull requests merged in 2022-04, with the labels that each got.

#241 [dispatcher] receive radio state event of simulated node
  dispatcher/dispatcher.go
Labels: enhancement

#257 [stress-test] relax ping test to allow collision-avoidance delay
  pylibs/stress_tests/ping_latency.py
Labels: enhancement, P4

#263 [github-actions] set fail-fast=false for matrixes
  .github/workflows/build.yml
  .github/workflows/develop.yml
  .github/workflows/stress.yml
  .github/workflows/test.yml
Labels: P4, continuous-integration
